apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-crud-service
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "crud-service"