FROM python:3.13-slim

WORKDIR /app

COPY grpc_client/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY grpc_client /app


COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

CMD ["/usr/local/bin/wait-for-it.sh", "kafka:9092", "--",  "python", "/app/client.py"]