apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce # Allows the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 GiB of storage for Grafana data