apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc-service  # Ensure this matches the label on your gRPC service pod
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  clusterIP: None  # Makes it headless (optional depending on your setup)
