apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: haseebr26/iot_gateway-grpc_client:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        volumeMounts:
        - name: grpc-client-data
          mountPath: /app/data # Adjust the path based on your application's requirements
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: grpc-client-data
        persistentVolumeClaim:
          claimName: grpc-client-pvc