global:
  scrape_interval: 5s

  scrape_timeout: 5s

  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "crud-service"
    static_configs:
      - targets: ["localhost:8000"]
        # Replace with "host.docker.internal:8000" if you're running Prometheus
        # in Docker on Windows or Mac, and your FastAPI service is on the host machine.