apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce # Allows the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 2Gi # Request 2 GiB of storage for Prometheus data