global:
  scrape_interval: 5s

  scrape_timeout: 5s

  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "crud-service"
    static_configs:
      - targets: ["crud_service:8000"]

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']

#send metrics to grafana

#remote_write:
#- url: <https://your-remote-write-endpoint>
#  basic_auth:
#    username: <your user name>
#    password: <Your Grafana.com API Key>


# grafana token: 